#!/usr/bin/env bash
#  Nginx server so that /redirect_me is redirecting to another page.

other_page="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/nicolas-castillo-salcedo-95b90a173;\n\t}"
match="server_name _;"

sed -i "/$match/a\\$other_page" /etc/nginx/sites-available/default

sudo service nginx restart
