#!/usr/bin/env bash
# Nginx server to have a custom 404
sudo apt-get -y update
sudo apt-get -y install nginx

other_page="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/nicolas-castillo-salcedo-95b90a173;\n\t}"
match="server_name _;"
sed -i "/$match/a\\$other_page" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/error404.html
other_page2="\n\terror_page 404 /error404.html;\n"
sed -i "/$match/a\\$other_page2" /etc/nginx/sites-available/default

add_header='\n\tadd_header X-Served-By $hostname;'
sed -i "/$match/a\\$add_header" /etc/nginx/sites-available/default

sudo service nginx restart
