#!/usr/bin/env bash
# This script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.
number=0
while ((number++ < 10))
do
    echo Holberton School
    if [ "$number" -eq 9 ]
    then
        echo Hi
    fi
done
