#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations
number=1
while [ $number -le 10 ]
do
    if [ $number = 4 ]
        then
        echo "bad luck"
        number=$(($number+1))
    elif [ $number = 8 ]
        then
        echo "good luck"
        number=$(($number+1))
    else
        echo "Holberton School"
        number=$(($number+1))
    fi
done
