#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
Hour=0
while ((Hour < 13))
do
    minute=0
    echo "Hour: $Hour"
    while ((minute++ < 59))
    do
        echo "$minute"
    done
    ((Hour++))
done
