#!/usr/bin/env bash
# This script that gives you information about the holbertonschool file_name.

f_name="holbertonschool"
if [ -e "$f_name" ]
then
	echo "holbertonschool f_name exists"
	if [ -s "$f_name" ]
	then
		echo "holbertonschool f_name is not empty"
	else
		echo "holbertonschool f_name is empty"
	fi
	if [ -f "$f_name" ]
	then
		echo "holbertonschool is a regular f_name"
	fi
else
	echo "holbertonschool f_name does not exist"
fi
